name: careless
channels:
  - conda-forge
dependencies:
- python=3.9
- pip
- cudatoolkit=11.2 
- cudnn=8.1.0
- numpy=1.26.4
- git
- openjdk=8
- pip:
  - tensorflow==2.10
  - n2v
  - csbdeep
  - scikit-image
  - tifffile
  - pandas
  - ipywidgets
  - python-javabridge
  - python-bioformats
  - jupyterlab
  - git+https://github.com/sommerc/careless.git

