name: careless3
channels:
  - conda-forge
dependencies:
- python=3.9
- pip
- cudatoolkit=11.2 
- cudnn=8.1.0
- pip:
  - tensorflow==2.10
  - n2v
  - csbdeep
  - scikit_image
  - tifffile
  - ipywidgets
  - python-javabridge
  - python-bioformats
  - jupyterlab
  - git+https://github.com/sommerc/careless.git

